# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=108)),
                ('hostip', models.GenericIPAddressField()),
                ('port', models.IntegerField(max_length=6)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
    ]
