# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pratice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='graduate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='crm_pratice.ClassList', verbose_name='班级列表'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consult_memo',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_pratice.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course_type',
            field=models.CharField(choices=[('online', '网络班'), ('offline_weekend', '面授班(周末)'), ('offline_fulltime', '面授班(脱产)')], default='offline_weekend', max_length=64, verbose_name='上课方式'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm_pratice.Customer', verbose_name='内部介绍'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source_type',
            field=models.CharField(choices=[('qq', 'qq群'), ('referral', '内部转介绍'), ('51cto', '51cto'), ('agent', '招生代理'), ('others', '其它')], max_length=64, verbose_name='咨询渠道'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('signed', '已报名'), ('unregistered', '未报名'), ('graduated', '已毕业'), ('drop-off', '退学')], max_length=64, verbose_name='当前状态'),
        ),
    ]
